# Generated by Django 3.0 on 2019-12-16 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filebot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='caption',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
