# Generated by Django 3.0 on 2019-12-23 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filebot', '0002_file_caption'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='share_photo',
            field=models.ImageField(blank=True, null=True, upload_to='share/'),
        ),
    ]
