# Generated by Django 3.0 on 2019-12-23 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filebot', '0003_settings_share_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
