# Generated by Django 3.0 on 2019-12-23 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filebot', '0004_file_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='unprintable_file_name',
            field=models.BooleanField(default=False),
        ),
    ]
