# Generated by Django 3.0 on 2019-12-23 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filebot', '0005_file_unprintable_file_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='file_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
