# Generated by Django 3.0 on 2019-12-26 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filebot', '0006_file_file_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='clicks',
            field=models.IntegerField(default=0),
        ),
    ]
