# Generated by Django 3.0 on 2019-12-26 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('filebot', '0007_category_clicks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='filebot.Category'),
        ),
    ]
