# Generated by Django 3.0 on 2019-12-28 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filebot', '0010_auto_20191228_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='hide_file_name',
            field=models.BooleanField(default=True),
        ),
    ]
